### ISSUE TITLE
Right arm is getting data from wrong source

### ISSUE THREAD

**Issue by zachkasica** [shinselrobots/astra_body_tracker#1]
On line 335 and below, in astra_body_tracker_node.cpp, the joint selected is the left shoulder, but the right shoulder data in the skeleton is being set. It should be ASTRA_JOINT_RIGHT_SHOULDER. This occurs for the right elbow and hand as well.

`joint = &body->joints[ASTRA_JOINT_LEFT_SHOULDER];`
`skeleton_data.joint_position_right_shoulder.x = ((astra_vector3f_t*)&joint->worldPosition)->z / 1000.0;`

**Comment by emiliavs** [comment]
Hi, were you able to build the node? I am having problems recognizing the variables from the .msg files. 
Eg:
error: ‘struct body_tracker_msgs::BodyTracker_<body_tracker_msgs::BodyTracker_<std::allocator<void> > >’ has no member named ‘centerOfMass’
           skeleton_data.centerOfMass.x = centerOfMass->z;

**Comment by shinselrobots** [comment]
Thanks for catching this!  I have checked in the corrected code, as well as other clean up.
please see the readme for more info.
