### ISSUE TITLE
could not make package

### ISSUE THREAD

**Issue by wouter1006** [shinselrobots/astra_body_tracker#3]
Hello all,

After cloning the astra_body_tracker and the body_tracker_msgs packages into the src of our catkin_ws running catkin_make gives us the following error:

          Path = /home/system/AstraSDK/samples/cmake/
	CMake Error at astra_body_tracker/CMakeLists.txt:30 (find_package):
	  By not providing "FindAstra.cmake" in CMAKE_MODULE_PATH this project has
	  asked CMake to find a package configuration file provided by "Astra", but
	  CMake did not find one.

	  Could not find a package configuration file provided by "Astra" with any of
	  the following names:

		AstraConfig.cmake
		astra-config.cmake

	  Add the installation prefix of "Astra" to CMAKE_PREFIX_PATH or set
	  "Astra_DIR" to a directory containing one of the above files.  If "Astra"
	  provides a separate development package or SDK, be sure it has been
	  installed.

	-- Configuring incomplete, errors occurred!
	See also "/home/wouter/catkin2_ws/build/CMakeFiles/CMakeOutput.log".
	See also "/home/wouter/catkin2_ws/build/CMakeFiles/CMakeError.log".
	Makefile:836: recipe for target 'cmake_check_build_system' failed
	make: *** [cmake_check_build_system] Error 1
	Invoking "make cmake_check_build_system" failed

We already set the directories in the CMakeList to our directories. We are using ROS Kinetic on Ubuntu 16.04. In the SDK package we can not find the AstraConfig.cmake file.

Does anyone know how to solve this error.

Thanks in advance!

**Comment by shinselrobots** [comment]
This code is a work in progress. Please wait a couple of weeks until I complete the development. 

I am moving to custom messages, and major code cleanup.

**Comment by shinselrobots** [comment]
Ok, changes are completed.  Feel free to try it.  Make sure to read the README.md, for installation instructions.

You will also need the body_tracker_msgs project.
